-- =====================================================================
-- Vastio · V1 · Esquema inicial (DER v2)
-- Generado a partir del diccionario de datos. PostgreSQL 16+.
-- =====================================================================

-- Persona que opera el sistema. La baja es lógica: se conserva el historial de lo que registró.
CREATE TABLE usuario (
    usuario_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_completo varchar(120) NOT NULL,
    nombre_usuario varchar(50) NOT NULL UNIQUE,
    hash_contrasena varchar(100) NOT NULL,
    email varchar(120),
    telefono varchar(30),
    debe_cambiar_contrasena boolean NOT NULL DEFAULT true,
    activo boolean NOT NULL DEFAULT true,
    fecha_alta timestamptz NOT NULL DEFAULT now(),
    fecha_baja timestamptz,
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id)
);

-- Perfil de usuario. Los códigos son fijos porque la autorización del backend los referencia.
CREATE TABLE rol (
    rol_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo varchar(20) NOT NULL UNIQUE,
    nombre varchar(50) NOT NULL,
    CONSTRAINT pk_rol PRIMARY KEY (rol_id),
    CONSTRAINT ck_rol_codigo CHECK (codigo IN ('DIRECCION', 'COORDINACION', 'ADMINISTRACION', 'VENDEDORA', 'PLANNER', 'COMPRAS', 'BARRA', 'COCINA'))
);

-- Asignación de perfiles. Un usuario puede tener más de un perfil (p. ej. vendedora que cubre como planner).
CREATE TABLE usuario_rol (
    usuario_id bigint NOT NULL,
    rol_id smallint NOT NULL,
    fecha_asignacion timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_usuario_rol PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_rol_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_usuario_rol_rol_id FOREIGN KEY (rol_id) REFERENCES rol (rol_id)
);

-- Parámetros escalares configurables sin intervención técnica.
CREATE TABLE parametro (
    clave varchar(60) NOT NULL,
    valor varchar(255) NOT NULL,
    descripcion varchar(255),
    CONSTRAINT pk_parametro PRIMARY KEY (clave)
);

-- Lista configurable de motivos para cancelaciones, reprogramaciones, bloqueos y ajustes de stock.
CREATE TABLE motivo (
    motivo_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ambito varchar(15) NOT NULL,
    nombre varchar(80) NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_motivo PRIMARY KEY (motivo_id),
    CONSTRAINT ck_motivo_ambito CHECK (ambito IN ('CANCELACION', 'REPROGRAMACION', 'BLOQUEO', 'AJUSTE')),
    CONSTRAINT uq_motivo_1 UNIQUE (ambito, nombre)
);

-- Salón del complejo.
CREATE TABLE salon (
    salon_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(40) NOT NULL UNIQUE,
    capacidad integer,
    codigo varchar(20) NOT NULL UNIQUE,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_salon PRIMARY KEY (salon_id),
    CONSTRAINT ck_salon_1 CHECK (capacidad IS NULL OR capacidad > 0)
);

-- Turno comercializable. Define el horario que usa el sistema para pasar el evento a En curso y a Realizado.
CREATE TABLE turno (
    turno_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo varchar(20) NOT NULL UNIQUE,
    nombre varchar(20) NOT NULL UNIQUE,
    hora_inicio time NOT NULL,
    hora_fin time NOT NULL,
    cruza_medianoche boolean NOT NULL,
    CONSTRAINT pk_turno PRIMARY KEY (turno_id)
);

-- Tipo de evento.
CREATE TABLE tipo_evento (
    tipo_evento_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(40) NOT NULL UNIQUE,
    usa_segmentos boolean NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_evento PRIMARY KEY (tipo_evento_id)
);

-- Segmento de asistencia.
CREATE TABLE tipo_segmento_asistencia (
    tipo_segmento_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(40) NOT NULL UNIQUE,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_segmento_asistencia PRIMARY KEY (tipo_segmento_id)
);

-- Categoría configurable de servicio contratado (decisión de Meli: sin desplegables fijos).
CREATE TABLE categoria_servicio (
    categoria_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(40) NOT NULL UNIQUE,
    orden smallint NOT NULL,
    visible_en_cocina boolean NOT NULL,
    requerida_para_confirmar boolean NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_categoria_servicio PRIMARY KEY (categoria_id)
);

-- Salón × fecha × turno. Se crea a demanda la primera vez que se la ocupa o bloquea. Es además el ancla de bloqueo pesimista (SELECT … FOR UPDATE) que evita que un evento y un bloqueo tomen la misma unidad en paralelo.
CREATE TABLE unidad_comercializable (
    unidad_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    salon_id smallint NOT NULL,
    fecha date NOT NULL,
    turno_id smallint NOT NULL,
    CONSTRAINT pk_unidad_comercializable PRIMARY KEY (unidad_id),
    CONSTRAINT fk_unidad_comercializable_salon_id FOREIGN KEY (salon_id) REFERENCES salon (salon_id),
    CONSTRAINT fk_unidad_comercializable_turno_id FOREIGN KEY (turno_id) REFERENCES turno (turno_id),
    CONSTRAINT uq_unidad_comercializable_1 UNIQUE (salon_id, fecha, turno_id)
);

-- Bloqueo de unidades por motivos no comerciales. No es un estado del Evento.
CREATE TABLE bloqueo (
    bloqueo_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    motivo_id smallint NOT NULL,
    detalle varchar(255),
    usuario_id bigint NOT NULL,
    fecha_registro timestamptz NOT NULL DEFAULT now(),
    activo boolean NOT NULL,
    usuario_desbloqueo_id bigint,
    fecha_desbloqueo timestamptz,
    CONSTRAINT pk_bloqueo PRIMARY KEY (bloqueo_id),
    CONSTRAINT fk_bloqueo_motivo_id FOREIGN KEY (motivo_id) REFERENCES motivo (motivo_id),
    CONSTRAINT fk_bloqueo_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_bloqueo_usuario_desbloqueo_id FOREIGN KEY (usuario_desbloqueo_id) REFERENCES usuario (usuario_id)
);

-- Unidades alcanzadas por un bloqueo. El rango de fechas y turnos de la pantalla se expande en una fila por unidad.
CREATE TABLE bloqueo_unidad (
    bloqueo_id bigint NOT NULL,
    unidad_id bigint NOT NULL,
    CONSTRAINT pk_bloqueo_unidad PRIMARY KEY (bloqueo_id, unidad_id),
    CONSTRAINT fk_bloqueo_unidad_bloqueo_id FOREIGN KEY (bloqueo_id) REFERENCES bloqueo (bloqueo_id),
    CONSTRAINT fk_bloqueo_unidad_unidad_id FOREIGN KEY (unidad_id) REFERENCES unidad_comercializable (unidad_id)
);

-- Persona u organización que contrata el evento.
CREATE TABLE cliente (
    cliente_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(120) NOT NULL,
    documento varchar(13),
    telefono varchar(30),
    email varchar(120),
    CONSTRAINT pk_cliente PRIMARY KEY (cliente_id)
);

-- Entidad central que vincula ambos módulos.
CREATE TABLE evento (
    evento_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo varchar(14) NOT NULL UNIQUE,
    unidad_id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    tipo_evento_id smallint NOT NULL,
    vendedora_id bigint NOT NULL,
    planner_id bigint,
    estado varchar(15) NOT NULL,
    nombre varchar(120) NOT NULL,
    cantidad_invitados integer,
    invitados_definitivos boolean NOT NULL,
    hora_inicio time,
    observaciones_internas text,
    importe_sena numeric(14,2),
    fecha_sena date,
    firmante_nombre varchar(120),
    firmante_dni varchar(10),
    firmante_contacto varchar(120),
    fecha_firma_contrato date,
    motivo_cancelacion_id smallint,
    detalle_cancelacion varchar(255),
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    version integer NOT NULL,
    CONSTRAINT pk_evento PRIMARY KEY (evento_id),
    CONSTRAINT fk_evento_unidad_id FOREIGN KEY (unidad_id) REFERENCES unidad_comercializable (unidad_id),
    CONSTRAINT fk_evento_cliente_id FOREIGN KEY (cliente_id) REFERENCES cliente (cliente_id),
    CONSTRAINT fk_evento_tipo_evento_id FOREIGN KEY (tipo_evento_id) REFERENCES tipo_evento (tipo_evento_id),
    CONSTRAINT fk_evento_vendedora_id FOREIGN KEY (vendedora_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_evento_planner_id FOREIGN KEY (planner_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_evento_motivo_cancelacion_id FOREIGN KEY (motivo_cancelacion_id) REFERENCES motivo (motivo_id),
    CONSTRAINT ck_evento_estado CHECK (estado IN ('PRE_RESERVA', 'SENADO', 'CONTRATADO', 'CONFIRMADO', 'EN_CURSO', 'REALIZADO', 'CERRADO', 'LIBERADA', 'CANCELADO')),
    CONSTRAINT ck_evento_1 CHECK (cantidad_invitados IS NULL OR cantidad_invitados >= 0),
    CONSTRAINT ck_evento_2 CHECK (importe_sena IS NULL OR importe_sena >= 0),
    CONSTRAINT ck_evento_3 CHECK (estado NOT IN ('SENADO','CONTRATADO','CONFIRMADO','EN_CURSO','REALIZADO','CERRADO') OR (importe_sena IS NOT NULL AND fecha_sena IS NOT NULL AND firmante_dni IS NOT NULL)),
    CONSTRAINT ck_evento_4 CHECK (estado NOT IN ('CONTRATADO','CONFIRMADO','EN_CURSO','REALIZADO','CERRADO') OR fecha_firma_contrato IS NOT NULL),
    CONSTRAINT ck_evento_5 CHECK (estado NOT IN ('CONFIRMADO','EN_CURSO','REALIZADO','CERRADO') OR (planner_id IS NOT NULL AND invitados_definitivos)),
    CONSTRAINT ck_evento_6 CHECK (estado <> 'CANCELADO' OR motivo_cancelacion_id IS NOT NULL)
);

-- Contactos del evento además del cliente (padre, madre, organizador).
CREATE TABLE contacto_evento (
    contacto_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    nombre varchar(120) NOT NULL,
    vinculo varchar(40),
    telefono varchar(30),
    email varchar(120),
    CONSTRAINT pk_contacto_evento PRIMARY KEY (contacto_id),
    CONSTRAINT fk_contacto_evento_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id)
);

-- Servicio acordado con el cliente, con descripción libre dentro de una categoría configurable.
CREATE TABLE servicio_contratado (
    servicio_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    categoria_id smallint NOT NULL,
    descripcion text NOT NULL,
    usuario_id bigint NOT NULL,
    fecha_modificacion timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_servicio_contratado PRIMARY KEY (servicio_id),
    CONSTRAINT fk_servicio_contratado_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_servicio_contratado_categoria_id FOREIGN KEY (categoria_id) REFERENCES categoria_servicio (categoria_id),
    CONSTRAINT fk_servicio_contratado_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id)
);

-- Asistencia prevista y real por segmento (egresados).
CREATE TABLE asistencia_segmento (
    asistencia_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    tipo_segmento_id smallint NOT NULL,
    cantidad_prevista integer,
    cantidad_real integer,
    CONSTRAINT pk_asistencia_segmento PRIMARY KEY (asistencia_id),
    CONSTRAINT fk_asistencia_segmento_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_asistencia_segmento_tipo_segmento_id FOREIGN KEY (tipo_segmento_id) REFERENCES tipo_segmento_asistencia (tipo_segmento_id),
    CONSTRAINT uq_asistencia_segmento_1 UNIQUE (evento_id, tipo_segmento_id),
    CONSTRAINT ck_asistencia_segmento_2 CHECK (cantidad_prevista IS NULL OR cantidad_prevista >= 0),
    CONSTRAINT ck_asistencia_segmento_3 CHECK (cantidad_real IS NULL OR cantidad_real >= 0)
);

-- Archivos del legajo. El archivo vive en el almacenamiento; la base guarda la referencia.
CREATE TABLE documento_evento (
    documento_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    tipo varchar(15) NOT NULL,
    nombre_archivo varchar(150) NOT NULL,
    ruta varchar(255) NOT NULL,
    mime_type varchar(60) NOT NULL,
    tamano_bytes integer NOT NULL,
    usuario_id bigint NOT NULL,
    fecha_carga timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_documento_evento PRIMARY KEY (documento_id),
    CONSTRAINT fk_documento_evento_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_documento_evento_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_documento_evento_tipo CHECK (tipo IN ('CONTRATO', 'PRESUPUESTO', 'OTRO')),
    CONSTRAINT ck_documento_evento_1 CHECK (tamano_bytes > 0)
);

-- Historial inalterable de transiciones (RNF-SEG-03). Solo inserción.
CREATE TABLE cambio_estado_evento (
    cambio_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    estado_anterior varchar(15),
    estado_nuevo varchar(15) NOT NULL,
    usuario_id bigint,
    fecha_hora timestamptz NOT NULL DEFAULT now(),
    observacion varchar(255),
    CONSTRAINT pk_cambio_estado_evento PRIMARY KEY (cambio_id),
    CONSTRAINT fk_cambio_estado_evento_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_cambio_estado_evento_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_cambio_estado_evento_estado_anterior CHECK (estado_anterior IN ('PRE_RESERVA', 'SENADO', 'CONTRATADO', 'CONFIRMADO', 'EN_CURSO', 'REALIZADO', 'CERRADO', 'LIBERADA', 'CANCELADO')),
    CONSTRAINT ck_cambio_estado_evento_estado_nuevo CHECK (estado_nuevo IN ('PRE_RESERVA', 'SENADO', 'CONTRATADO', 'CONFIRMADO', 'EN_CURSO', 'REALIZADO', 'CERRADO', 'LIBERADA', 'CANCELADO'))
);

-- Registro de cambios de datos del evento (Modificar evento). Solo inserción.
CREATE TABLE modificacion_evento (
    modificacion_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    campo varchar(60) NOT NULL,
    valor_anterior text,
    valor_nuevo text,
    usuario_id bigint NOT NULL,
    fecha_hora timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_modificacion_evento PRIMARY KEY (modificacion_id),
    CONSTRAINT fk_modificacion_evento_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_modificacion_evento_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id)
);

-- Cambio de unidad de un evento. Conserva la programación original. No cambia el estado.
CREATE TABLE reprogramacion (
    reprogramacion_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    unidad_anterior_id bigint NOT NULL,
    unidad_nueva_id bigint NOT NULL,
    motivo_id smallint NOT NULL,
    detalle varchar(255),
    usuario_id bigint NOT NULL,
    fecha_hora timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_reprogramacion PRIMARY KEY (reprogramacion_id),
    CONSTRAINT fk_reprogramacion_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_reprogramacion_unidad_anterior_id FOREIGN KEY (unidad_anterior_id) REFERENCES unidad_comercializable (unidad_id),
    CONSTRAINT fk_reprogramacion_unidad_nueva_id FOREIGN KEY (unidad_nueva_id) REFERENCES unidad_comercializable (unidad_id),
    CONSTRAINT fk_reprogramacion_motivo_id FOREIGN KEY (motivo_id) REFERENCES motivo (motivo_id),
    CONSTRAINT fk_reprogramacion_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_reprogramacion_1 CHECK (unidad_anterior_id <> unidad_nueva_id)
);

-- Aviso generado por un cambio de evento.
CREATE TABLE notificacion (
    notificacion_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint,
    tipo varchar(30) NOT NULL,
    mensaje varchar(255) NOT NULL,
    usuario_origen_id bigint,
    fecha_hora timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_notificacion PRIMARY KEY (notificacion_id),
    CONSTRAINT fk_notificacion_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_notificacion_usuario_origen_id FOREIGN KEY (usuario_origen_id) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_notificacion_tipo CHECK (tipo IN ('EVENTO_NUEVO', 'SENA', 'CONTRATO', 'CONFIRMACION', 'MODIFICACION', 'REPROGRAMACION', 'CANCELACION', 'PLANNER_ASIGNADA', 'ALERTA_STOCK'))
);

-- Destinatarios de cada aviso. El ruteo por perfil y dato modificado se resuelve al crear el aviso.
CREATE TABLE notificacion_destinatario (
    notificacion_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    leida boolean NOT NULL DEFAULT false,
    fecha_lectura timestamptz,
    CONSTRAINT pk_notificacion_destinatario PRIMARY KEY (notificacion_id, usuario_id),
    CONSTRAINT fk_notificacion_destinatario_notificacion_id FOREIGN KEY (notificacion_id) REFERENCES notificacion (notificacion_id),
    CONSTRAINT fk_notificacion_destinatario_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id)
);

-- Clasificación de bebidas.
CREATE TABLE tipo_bebida (
    tipo_bebida_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(40) NOT NULL UNIQUE,
    CONSTRAINT pk_tipo_bebida PRIMARY KEY (tipo_bebida_id)
);

-- Forma en que se mueve la mercadería.
CREATE TABLE unidad_manipulacion (
    unidad_manipulacion_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(20) NOT NULL UNIQUE,
    CONSTRAINT pk_unidad_manipulacion PRIMARY KEY (unidad_manipulacion_id)
);

-- Proveedor de bebida (carga inicial de datos maestros).
CREATE TABLE proveedor (
    proveedor_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    razon_social varchar(120) NOT NULL,
    cuit varchar(11) UNIQUE,
    telefono varchar(30),
    email varchar(120),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_proveedor PRIMARY KEY (proveedor_id)
);

-- Artículo del catálogo. Toda cantidad del sistema se expresa en su unidad base (botella).
CREATE TABLE bebida (
    bebida_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(100) NOT NULL,
    presentacion varchar(40) NOT NULL,
    tipo_bebida_id smallint NOT NULL,
    unidad_manipulacion_id smallint NOT NULL,
    unidades_por_bulto smallint NOT NULL,
    precio_referencia numeric(14,2) NOT NULL,
    stock_minimo numeric(10,2),
    proveedor_habitual_id bigint,
    activo boolean NOT NULL,
    fecha_baja timestamptz,
    CONSTRAINT pk_bebida PRIMARY KEY (bebida_id),
    CONSTRAINT fk_bebida_tipo_bebida_id FOREIGN KEY (tipo_bebida_id) REFERENCES tipo_bebida (tipo_bebida_id),
    CONSTRAINT fk_bebida_unidad_manipulacion_id FOREIGN KEY (unidad_manipulacion_id) REFERENCES unidad_manipulacion (unidad_manipulacion_id),
    CONSTRAINT fk_bebida_proveedor_habitual_id FOREIGN KEY (proveedor_habitual_id) REFERENCES proveedor (proveedor_id),
    CONSTRAINT ck_bebida_1 CHECK (unidades_por_bulto > 0),
    CONSTRAINT ck_bebida_2 CHECK (precio_referencia >= 0)
);

-- Códigos de barras de un artículo. Un artículo puede tener varios (botella y cajón).
CREATE TABLE codigo_barra (
    codigo varchar(20) NOT NULL,
    bebida_id bigint NOT NULL,
    unidades smallint NOT NULL,
    CONSTRAINT pk_codigo_barra PRIMARY KEY (codigo),
    CONSTRAINT fk_codigo_barra_bebida_id FOREIGN KEY (bebida_id) REFERENCES bebida (bebida_id),
    CONSTRAINT ck_codigo_barra_1 CHECK (unidades > 0)
);

-- Depósito, sector, depósito de transición o barra. Configurable: el circuito funciona con o sin transición.
CREATE TABLE ubicacion (
    ubicacion_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(60) NOT NULL UNIQUE,
    tipo varchar(12) NOT NULL,
    ubicacion_padre_id smallint,
    salon_id smallint,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_ubicacion PRIMARY KEY (ubicacion_id),
    CONSTRAINT fk_ubicacion_ubicacion_padre_id FOREIGN KEY (ubicacion_padre_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_ubicacion_salon_id FOREIGN KEY (salon_id) REFERENCES salon (salon_id),
    CONSTRAINT ck_ubicacion_tipo CHECK (tipo IN ('DEPOSITO', 'SECTOR', 'TRANSICION', 'BARRA')),
    CONSTRAINT ck_ubicacion_1 CHECK (tipo <> 'SECTOR' OR ubicacion_padre_id IS NOT NULL),
    CONSTRAINT ck_ubicacion_2 CHECK (tipo <> 'BARRA' OR salon_id IS NOT NULL)
);

-- Saldo teórico por ubicación y artículo. Se actualiza en la misma transacción que cada movimiento; puede ser negativo (señal de un registro faltante, genera alerta).
CREATE TABLE stock_ubicacion (
    ubicacion_id smallint NOT NULL,
    bebida_id bigint NOT NULL,
    cantidad numeric(10,2) NOT NULL,
    fecha_actualizacion timestamptz NOT NULL,
    CONSTRAINT pk_stock_ubicacion PRIMARY KEY (ubicacion_id, bebida_id),
    CONSTRAINT fk_stock_ubicacion_ubicacion_id FOREIGN KEY (ubicacion_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_stock_ubicacion_bebida_id FOREIGN KEY (bebida_id) REFERENCES bebida (bebida_id)
);

-- Cabecera de un ingreso de mercadería al depósito.
CREATE TABLE ingreso (
    ingreso_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ubicacion_destino_id smallint NOT NULL,
    proveedor_id bigint,
    numero_remito varchar(30),
    fecha_ingreso date NOT NULL DEFAULT current_date,
    es_inventario_inicial boolean NOT NULL,
    usuario_id bigint NOT NULL,
    fecha_registro timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_ingreso PRIMARY KEY (ingreso_id),
    CONSTRAINT fk_ingreso_ubicacion_destino_id FOREIGN KEY (ubicacion_destino_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_ingreso_proveedor_id FOREIGN KEY (proveedor_id) REFERENCES proveedor (proveedor_id),
    CONSTRAINT fk_ingreso_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id)
);

-- Propuesta de bebida a retirar para un evento confirmado.
CREATE TABLE orden_preparacion (
    orden_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    estado varchar(12) NOT NULL,
    ubicacion_origen_id smallint NOT NULL,
    ubicacion_destino_id smallint NOT NULL,
    responsable_id bigint NOT NULL,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    fecha_confirmacion timestamptz,
    CONSTRAINT pk_orden_preparacion PRIMARY KEY (orden_id),
    CONSTRAINT fk_orden_preparacion_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_orden_preparacion_ubicacion_origen_id FOREIGN KEY (ubicacion_origen_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_orden_preparacion_ubicacion_destino_id FOREIGN KEY (ubicacion_destino_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_orden_preparacion_responsable_id FOREIGN KEY (responsable_id) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_orden_preparacion_estado CHECK (estado IN ('SUGERIDA', 'MODIFICADA', 'CONFIRMADA', 'DESCARTADA', 'CERRADA'))
);

-- Renglón de la orden.
CREATE TABLE detalle_orden_preparacion (
    detalle_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    orden_id bigint NOT NULL,
    bebida_id bigint NOT NULL,
    cantidad_sugerida numeric(10,2) NOT NULL,
    cantidad_a_retirar numeric(10,2) NOT NULL,
    CONSTRAINT pk_detalle_orden_preparacion PRIMARY KEY (detalle_id),
    CONSTRAINT fk_detalle_orden_preparacion_orden_id FOREIGN KEY (orden_id) REFERENCES orden_preparacion (orden_id),
    CONSTRAINT fk_detalle_orden_preparacion_bebida_id FOREIGN KEY (bebida_id) REFERENCES bebida (bebida_id),
    CONSTRAINT uq_detalle_orden_preparacion_1 UNIQUE (orden_id, bebida_id),
    CONSTRAINT ck_detalle_orden_preparacion_2 CHECK (cantidad_sugerida >= 0),
    CONSTRAINT ck_detalle_orden_preparacion_3 CHECK (cantidad_a_retirar >= 0)
);

-- Entrega abierta de un evento hacia una barra. Agrupa la salida inicial y los retiros adicionales.
CREATE TABLE entrega (
    entrega_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evento_id bigint NOT NULL,
    ubicacion_destino_id smallint NOT NULL,
    orden_id bigint,
    estado varchar(10) NOT NULL,
    usuario_apertura_id bigint NOT NULL,
    fecha_apertura timestamptz NOT NULL DEFAULT now(),
    usuario_cierre_id bigint,
    fecha_cierre timestamptz,
    CONSTRAINT pk_entrega PRIMARY KEY (entrega_id),
    CONSTRAINT fk_entrega_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_entrega_ubicacion_destino_id FOREIGN KEY (ubicacion_destino_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_entrega_orden_id FOREIGN KEY (orden_id) REFERENCES orden_preparacion (orden_id),
    CONSTRAINT fk_entrega_usuario_apertura_id FOREIGN KEY (usuario_apertura_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_entrega_usuario_cierre_id FOREIGN KEY (usuario_cierre_id) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_entrega_estado CHECK (estado IN ('ABIERTA', 'CERRADA')),
    CONSTRAINT uq_entrega_1 UNIQUE (evento_id, ubicacion_destino_id)
);

-- Asiento inalterable de mercadería (RNF-SEG-03). Solo inserción: las correcciones son nuevos asientos de ajuste.
CREATE TABLE movimiento_stock (
    movimiento_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo varchar(18) NOT NULL,
    bebida_id bigint NOT NULL,
    cantidad numeric(10,2) NOT NULL,
    ubicacion_origen_id smallint,
    ubicacion_destino_id smallint,
    evento_id bigint,
    entrega_id bigint,
    ingreso_id bigint,
    movimiento_corregido_id bigint,
    motivo_id smallint,
    observacion varchar(255),
    usuario_id bigint NOT NULL,
    fecha_hora timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_movimiento_stock PRIMARY KEY (movimiento_id),
    CONSTRAINT fk_movimiento_stock_bebida_id FOREIGN KEY (bebida_id) REFERENCES bebida (bebida_id),
    CONSTRAINT fk_movimiento_stock_ubicacion_origen_id FOREIGN KEY (ubicacion_origen_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_movimiento_stock_ubicacion_destino_id FOREIGN KEY (ubicacion_destino_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_movimiento_stock_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_movimiento_stock_entrega_id FOREIGN KEY (entrega_id) REFERENCES entrega (entrega_id),
    CONSTRAINT fk_movimiento_stock_ingreso_id FOREIGN KEY (ingreso_id) REFERENCES ingreso (ingreso_id),
    CONSTRAINT fk_movimiento_stock_movimiento_corregido_id FOREIGN KEY (movimiento_corregido_id) REFERENCES movimiento_stock (movimiento_id),
    CONSTRAINT fk_movimiento_stock_motivo_id FOREIGN KEY (motivo_id) REFERENCES motivo (motivo_id),
    CONSTRAINT fk_movimiento_stock_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_movimiento_stock_tipo CHECK (tipo IN ('INGRESO', 'INVENTARIO_INICIAL', 'SALIDA_BARRA', 'RETIRO_ADICIONAL', 'DEVOLUCION', 'REMANENTE', 'AJUSTE', 'MERMA')),
    CONSTRAINT ck_movimiento_stock_1 CHECK (cantidad > 0),
    CONSTRAINT ck_movimiento_stock_2 CHECK (ubicacion_origen_id IS NOT NULL OR ubicacion_destino_id IS NOT NULL),
    CONSTRAINT ck_movimiento_stock_3 CHECK (tipo NOT IN ('SALIDA_BARRA','RETIRO_ADICIONAL','DEVOLUCION','REMANENTE') OR evento_id IS NOT NULL),
    CONSTRAINT ck_movimiento_stock_4 CHECK (tipo NOT IN ('AJUSTE','MERMA') OR motivo_id IS NOT NULL)
);

-- Resultado del cierre por artículo, congelado. Un cambio posterior del precio de referencia no altera el costo de eventos cerrados.
CREATE TABLE consumo_evento (
    evento_id bigint NOT NULL,
    bebida_id bigint NOT NULL,
    cantidad_entregada numeric(10,2) NOT NULL,
    cantidad_devuelta numeric(10,2) NOT NULL,
    cantidad_remanente numeric(10,2) NOT NULL,
    cantidad_consumida numeric(10,2) NOT NULL,
    precio_referencia_aplicado numeric(14,2) NOT NULL,
    costo_total numeric(14,2) NOT NULL,
    CONSTRAINT pk_consumo_evento PRIMARY KEY (evento_id, bebida_id),
    CONSTRAINT fk_consumo_evento_evento_id FOREIGN KEY (evento_id) REFERENCES evento (evento_id),
    CONSTRAINT fk_consumo_evento_bebida_id FOREIGN KEY (bebida_id) REFERENCES bebida (bebida_id)
);

-- Estimación de consumo por asistente según tipo de evento. Alimenta la orden sugerida mientras no hay histórico propio.
CREATE TABLE proporcion_consumo (
    proporcion_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_evento_id smallint NOT NULL,
    bebida_id bigint NOT NULL,
    botellas_por_asistente numeric(8,4) NOT NULL,
    CONSTRAINT pk_proporcion_consumo PRIMARY KEY (proporcion_id),
    CONSTRAINT fk_proporcion_consumo_tipo_evento_id FOREIGN KEY (tipo_evento_id) REFERENCES tipo_evento (tipo_evento_id),
    CONSTRAINT fk_proporcion_consumo_bebida_id FOREIGN KEY (bebida_id) REFERENCES bebida (bebida_id),
    CONSTRAINT uq_proporcion_consumo_1 UNIQUE (tipo_evento_id, bebida_id),
    CONSTRAINT ck_proporcion_consumo_2 CHECK (botellas_por_asistente >= 0)
);

-- Exclusividad de la unidad comercializable: un solo evento activo por salón + fecha + turno
CREATE UNIQUE INDEX ux_evento_unidad_activa ON evento (unidad_id) WHERE estado NOT IN ('LIBERADA','CANCELADO');
-- Una sola orden de preparación vigente por evento
CREATE UNIQUE INDEX ux_orden_evento_vigente ON orden_preparacion (evento_id) WHERE estado <> 'DESCARTADA';
-- Secuencia para el código legible del evento (EV-AAAA-NNNNN)
CREATE SEQUENCE evento_codigo_seq START 1;
-- Índices de consulta frecuente
CREATE INDEX ix_unidad_fecha ON unidad_comercializable (fecha);
CREATE INDEX ix_evento_estado ON evento (estado);
CREATE INDEX ix_evento_vendedora ON evento (vendedora_id);
CREATE INDEX ix_evento_planner ON evento (planner_id);
CREATE INDEX ix_cambio_estado_evento ON cambio_estado_evento (evento_id, fecha_hora);
CREATE INDEX ix_modificacion_evento ON modificacion_evento (evento_id, fecha_hora);
CREATE INDEX ix_notif_dest_pendientes ON notificacion_destinatario (usuario_id) WHERE NOT leida;
CREATE INDEX ix_mov_evento ON movimiento_stock (evento_id);
CREATE INDEX ix_mov_bebida_fecha ON movimiento_stock (bebida_id, fecha_hora);
CREATE INDEX ix_mov_entrega ON movimiento_stock (entrega_id);
